[[constraint]]
  version = "v1.10.1"
  name = "github.com/pulumi/pulumi"

[[constraint]]
  version = "v1.14.0"
  name = "github.com/pulumi/pulumi-azure"

[[constraint]]
  version = "v1.5.0"
  name = "github.com/pulumi/pulumi-azuread"

[prune]
  go-tests = true
  unused-packages = true
